### ISSUE TITLE
Docker image for a created environment

### ISSUE THREAD

**Issue by LidoDev** [mockoon/cli#2]
After fetching all the issues, i think there is no CLI feature to run a created environment.
The use case is to generate a docker image for the created environment and run it to mock a rest api web service.

Feature: generate a docker image or a war file or an executable file for a dedicated environment.

**Comment by mauriceackel** [comment]
@255kb Is the goal to simply put the cli into a docker container? Because from how I read the original issue, the question was, whether the cli would kinda "export" a docker container with the mocked API in it. This makes somewhat sense as we need the Mockoon file in the container.
However, I would rather suggest to put the CLI into a container and allow to pass the required parameters (as well as link an external file to the container FS) when spinning it up.

**Comment by 255kb** [comment]
@mauriceackel The original issue is quite old things changed as the CLI is now available. So, I don't think we are biased toward any implementation. 
I am not a Docker specialist, but I had envisioned your second option where where you would build an image containing the CLI and pass the parameters (`--data`, `--index`, etc) at runtime.
But it would also make sense to be able to build an image already including a data file, so everything is self sufficient. Maybe this could come later. 
Again, I am not a specialist. I know how to mount a volume but I would have to learn a little bit how to do things like this. So, if you want you can contribute and work on this. It would be more than welcomed!

**Comment by mauriceackel** [comment]
Count me in :)

**Comment by 255kb** [comment]
@mauriceackel I realize you are the one who tried to transform the app into a CLI 😄 Thank you for your ongoing support and enthusiasm!

**Comment by mauriceackel** [comment]
@255kb Now that I think about it, wouldn't we need to be able to pass a list of environments (and also an 'all' option) to the start command? Otherwise, the container could only ever run one environment..
On the other hand, it might make most sense to run only one environment per container in the first place.

**Comment by 255kb** [comment]
Good question. I know that there are opened issue on the main app to start all environments at once. It makes sense especially when people are mocking micro services. 
However, I would rather work on the Docker file without this option, and tackle it later in a separated issue.

**Comment by andy-ta** [comment]
Hi again @mauriceackel! I'm glad to see you're taking on this endeavor. Just to let you know that my team has been using the image from the Dockerfile I merged into your project without any issues almost everyday. Definitely you can use that as a starting point!

**Comment by mauriceackel** [comment]
@andy-ta Pleased to hear this 🎉 However, as this is a new project with a new structure I will need to start from scratch, but it should not be too difficult (famous last words)

Talking about it, @255kb there is another issue, namely that the CLI process will terminate after spinning up the background processes. So I was wondering how you think we should deal with it.. I could try to find some quick fix so that there is always some process running with PID 1 in the container but maybe we should take a different approach here.

**Comment by 255kb** [comment]
@mauriceackel I am not sure how to overcome this without doing some research. How do *they* do it with nginx and other applications like this? I had the impression that the application is launched at runtime as a background process, and the container continues running.

**Comment by mauriceackel** [comment]
@255kb For nginx, there is a CLI option `deamon off`, which basically keeps the process in the foreground

**Comment by 255kb** [comment]
@mauriceackel I forgot about this detail 😄 

I saw that you can run wrapper scripts forever https://docs.docker.com/config/containers/multi-service_container/ 
I don't know if it would be a good solution. 
Also, one trick you can try, is to comment out the `processManager.disconnect()` in the CLI. it prevents PM2 from exiting and keeps the CLI running forever. 
But then I wonder how you can run other commands like `mockoon stop` or `list` if the `start` command is running forever in the foreground. 🤔 
I realize that my knowledge of Docker is quite rudimentary.

**Comment by mauriceackel** [comment]
Yeah, I am currently trying to use a start script like this:
```
#!/bin/bash

mockoon start "$@"
sleep infinity & wait $!
```

Which should keep the container awake util a sigterm is received.. However, there seems to be some inconsistencies between implementations w.r.t. how 'infinity' ia actually defined 😅

**Comment by mauriceackel** [comment]
Regarding your suggestion: I guess if we could make the `processManager.disconnect()` work, we could add a `deamon off` argument, which will keep the start command alive and if it receives a SIGTERM, simply kills all processes.

**Comment by 255kb** [comment]
@mauriceackel Sure we could add such param if it is the normal way of doing things with Docker. But I feel like we should find something else than avoiding to disconnect PM2. It's still useful when testing but it feels a little bit "hacky" to me. I will investigate.
