### ISSUE TITLE
Get infos from *-out.log file to stdout docker

### ISSUE THREAD

**Issue by tmarmillot** [mockoon/cli#33]
**Is your feature request related to a problem? Please describe.**

I'm doing an integration test for requests with mockoon-cli inside docker. 

The context is to send webhooks to a client with a given url (example : PUT /v1/request) and verify that I hit the good mocked request.

In order to make it, I'm streaming stdout log from my container and waiting for status code "200" but the only stdout I get is :
 
``` 
Mock started at http://localhost:3000/ (pid: 0, name: mockoon-integration-test)
```

Inside the container we can see a log file : `~./mockoon-cli/logs/*-out.log` which have all needed informations : 

```
{"message":"Server started on port 3000","level":"info","timestamp":"2021-06-08T09:11:18.927Z"}
{"message":"PUT /v1/request | 200","level":"info","timestamp":"2021-06-08T09:11:22.470Z"}
```

**Describe the solution you'd like**

exemple stdout log I would like : 
``` 
INFO : Mock started at http://localhost:3000/ (pid: 0, name: mockoon-integration-test)
INFO : PUT /v1/request with return status code :  200
```

Environment : 
- Mockoon-cli (Docker)  : 1.0.1

**Comment by 255kb** [comment]
I guess this would be easier to implement if #43 is done. Dockerized Mockoon CLI could run as a blocking app (like nginx daemon off). 
Then we would need to output the logs to stdout instead of a file. 
One question though. The current log format is JSON. And I just added an option to log the full transaction (request body, etc) with #34. Could it work for you to have the logs in stdout in JSON too?

**Comment by tmarmillot** [comment]
Great ! 

Feel free to contact me if you need tester ! 🙂
