### ISSUE TITLE
Add flag to force repair when automating deployment

### ISSUE THREAD

**Issue by skalpeliio** [mockoon/cli#50]
**Describe the bug**
If I try run CLI by >>mockoon-cli start...,, the information is appear: 

 "This environment does not seem to be a valid Mockoon environment or is too old. Load it anyway? (Mockoon CLI will attempt to repair it)" 

there is no parameter that can be used to avoid this message. It is problematic to create an automaton for CLI
Additionality I use "export current environment to OpenAPI v3" and when I try start by CLI on port for example 8090 I have information that started on port 3000. 

![image](https://user-images.githubusercontent.com/24699415/144515523-be008e37-52f1-42d0-aeba-5d3aba888df3.png)

![image](https://user-images.githubusercontent.com/24699415/144515577-7f8c6585-2064-45da-a59d-ef264c3b86ad.png)

**Mockoon version:**
1.17.0

**OS / OS version:**
Windows Server

----------------

**Comment by 255kb** [comment]
Mockoon CLI is not able to run OpenAPI specification directly (yet). There is an open issue for this #18.
What really happens when you do this: 
- Mockoon detect that the content does not look like a Mockoon environment
- Mockoon prompt you to migrate and/or repair it
- you answer yes, Mockoon will fail to repair or convert anything and will completely overwrite the content. 

You can check the result of this in the `~/.mockoon-cli/data/` folder as the CLI copy the file temporarily before running the mock. 

I still agree that this message may be annoying when automating CLI usage. We should add a `--repair` or a `--yes` flag. 
I will update the issue title to reflect this.
