### ISSUE TITLE
Run multiple environment at once

### ISSUE THREAD

**Issue by 255kb** [mockoon/cli#57]
**Is your feature request related to a problem? Please describe.**
As import/export in mockoon format will be deprecated soon (https://github.com/mockoon/mockoon/issues/626) the only benefit of being able to run multiple environments at once with the `--all` flag will be lost. 

**Describe the solution you'd like**
Add a way to run multiple environments at once like: 
`mockoon-cli start --data ./file1.json,./file2.json`

- This should be compatible with the `daemon-off` flag so a single CLI can run multiple mocks on multiple ports. 
- `--port` flag should also be update to accept as many ports as environment files were passed: `--port 3000,3001,3002`
- `--pname` flag should also be update to accept as many process name as environment files were passed: `--pname p1,p2,p3`

**Comment by Kyoku57** [comment]
Hi, just to know ... on WSL2, if I try to start a Mockoon CLI through a docker-compose with the --all flag and a global json export, I will be rejected because of the --daemon-flag.
Is it related to this issue too ? I supposed it recommended to run each environment in seperated containers until this feature will be activated ?
